### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by fazpu** [aaronksaunders/ionic3-ngrx4-angularfire#1]
This line causes an import error:
`
import { firebaseProps } from './../environment'
`

Please, include an example file. The /src/environment is included in  the .gitignore ...

**Comment by aaronksaunders** [comment]
Must export the config, create a file in the `/src/environment.ts` that looks like this..

https://github.com/aaronksaunders/ionic3-ngrx4-angularfire/blob/master/src/app/app.module.ts#L26

```
// Must export the config, create a file in the /src/environment.ts that
// looks like this..
//
// export const firebaseProps = {
//     "apiKey": " ",
//     "authDomain": " ",
//     "databaseURL": " ",
//     "projectId": " ",
//     "storageBucket": " ",
//     "messagingSenderId": ""
// }
```
